baseURL = "https://storj.io/"
languageCode = "en-us"
title = "storj.io"

[permalinks]
  404 = "/404/"
  developers = "/developers/"
  community = "/community/"
  partners = "/partners/"
  privacy-policy = "/privacy-policy/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  code-of-conduct = "/code-of-conduct/"
  information-policy = "/information-policy/"
  storage-sla = "/storage-sla/"
  canary = "/canary/"
  whitepaper = "/whitepaper/"
  team = "/team/"
  careers = "/careers/"
  press = "/press/"
  press-kit = "/press-kit/"
  open-source = "/open-source/"
  sign-up = "/sign-up/"
  sign-up-farmer = "/sign-up-farmer/"
  storj-share-information = "/storj-share-information/"
  community-reporting = "/community-reporting/"
  storage-node-estimator = "/storage-node-estimator/"
  storj-share-terms = "/storj-share-terms/"
  spanish-invite = "/spanish-invite/"
  german-invite = "/german-invite/"
  russian-invite = "/russian-invite/"
  mandarin-invite = "/mandarin-invite/"
  sign-up-success = "/sign-up-success/"
  thankyou = "/thankyou/"
