[[redirects]]
  from = "/blog/*"
  to = "https://thirsty-austin-89166b.netlify.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/clone"
  to = "https://gist.githubusercontent.com/zeebo/ecc0abd0aec09c9eff85b12d788dfc81/raw/storj-clone"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    Strict-Transport-Security = "max-age=300; includeSubDomains"
    Content-Security-Policy = "default-src 'none'; script-src 'self' www.google-analytics.com ajax.googleapis.com www.googletagmanager.com *.segment.com *.pingdom.net identity.netlify.com unpkg.com static.addtoany.com; connect-src 'self' *.segment.io *.pingdom.net; img-src 'self'; style-src 'self' fonts.googleapis.com; base-uri 'self'; form-action 'self'; font-src 'self' fonts.gstatic.com; child-src 'self' www.googletagmanager.com www.youtube.com *.vimeo.com;"
