apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- if .Values.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: 104.200.143.66/32,104.196.58.99/32
{{- end }}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
spec:
  rules:
  - host: {{ .Values.redirect.subdomain }}.{{ .Values.fqdn }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.redirect.subdomain }}.{{ .Values.fqdn }}
    secretName: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}-tls
